### ISSUE TITLE
Infinite loop on host discovery

### ISSUE THREAD

**Issue by techwolf359** [outbrain/orchestrator#64] opened 2015-05-26 22:15 UTC
DEBUG logs show continuous scrolling on discovery of 2 hosts. From a fresh start, 140k lines logged in a few minutes.

**Comment by shlomi-noach** [comment] 2015-05-27 09:02
Hi @techwolf359 , yes, I also found out the same. Please see if https://github.com/outbrain/orchestrator/releases/tag/v1.4.131 (released yesterday) fixes that for you

**Comment by shlomi-noach** [comment] 2015-05-27 09:05
OK, I see the problem is not resolved in 1.4.131 and I've removed the release. Will fix.

**Comment by shlomi-noach** [comment] 2015-05-27 09:10
as immediate attempt to fix the problem, could you please call upon `/api/reset-hostname-resolve-cache` and see if this helps?
or otherwise `DELETE FROM hostname_resolve` directly on backend db?

**Comment by shlomi-noach** [comment] 2015-05-28 10:47
Please test https://github.com/outbrain/orchestrator/releases/tag/v1.4.135

**Comment by shlomi-noach** [comment] 2015-05-28 20:25
According to @techwolf359 this solves the issue.

**Closed by shlomi-noach** 2015-05-28 20:25 UTC
